# -*- coding: utf-8 -*-
"""DAA.P2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DF8kLK9NDjwXFqMdLMyguPu_vj0paV2W
"""

import numpy as np
print(np.__version__)

print("HelloWorld!")

print("Nama Saya Rizki Fadillah")

print("NIM saya 2020071015")

if 5 > 2:
  print("Five is greater than two!")

x=5
y="John"
print(x)
print(y)

x=4
x="Sally"
print(x)

def getFirst(myList):
  return myList[0]
getFirst([1,2,3])

def getSec(myList):
  return myList[1]
getSec([1,2,3])

def getLast(myList):
  return myList[2]
getLast([1,2,3])

def getSum(myList):
  sum = 0
  for item in myList:
    sum = sum + item
  return sum

getSum([1,2,3,4])

getSum([1,2,3])

def getKali(myList):
  sum = 1
  for item in myList:
    sum = sum*item
  return sum
getKali([1,2,3,4])

def getBagi(myList):
  sum = 100
  for item in myList:
    sum = sum/item
  return sum
getBagi([25, 2])

def getSum(myList):
  sum=0
  for row in myList:
    for item in row:
      sum+=item
  return sum

getSum([[1,2,5],[3,4,7]])

def getBagi(myList):
  sum=1200
  for row in myList:
    for item in row:
      sum /= item
  return sum

getBagi([[10,2],[5,1]])

def getMin(myList):
  min=32
  for row in myList:
    for item in row:
      min -= item
  return min

getMin([[10,2],[5,1]])

def searchBinary(myList, item):
  first = 0
  last = len(myList)-1
  foundFlag = False
  while( first<= last and not foundFlag):
    mid = (first + last)//2
    if myList[mid] == item :
       foundFlag = True
    else :
      if item < myList[mid]:
        last = mid - 1
      else:
        first = mid + 1
  return foundFlag

searchBinary([8,9,10,100,1000,2000,3000], 10)

searchBinary([8,9,10,100,1000,2000,3000], 50)